spring:
  application:
    name: auth-server-graalvm
  security:
    oauth2:
      authorizationserver:
        registration:
          client:
            client-id: client
            client-secret: "$2a$10$BzYDKFlb7Tw604vQdPTmsO96g.jsDVjpvMJIgaJXkzukAX6SEqwM6"
            client-authentication-methods:
              - client_secret_basic
              - client_secret_post
            authorization-grant-types:
              - client_credentials
            scopes:
              - read
              - write

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
